"""Turn a fresh clone into a named project. Run once, after editing project.toml.

    python scripts/setup.py

Validates project.toml, writes backend/api/.env and frontend/web/.env from it,
renders the starter harness's agentcore config (unless harness.arn is set),
then deletes itself. Re-running is safe: if both .env files exist it reports
that setup is already complete and changes nothing.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "infra"))

import config  # noqa: E402
import harness_files  # noqa: E402

BACKEND_ENV = ROOT / "backend" / "api" / ".env"
FRONTEND_ENV = ROOT / "frontend" / "web" / ".env"


def backend_env(c: config.Config) -> str:
    return f"""\
# Generated by scripts/setup.py from project.toml. Local development only.
PROJECT_NAME={c.name}
AWS_REGION={c.aws_region}
SESSIONS_TABLE_NAME={c.sessions_table}
ITEMS_TABLE_NAME={c.items_table}
# Empty until the starter harness is deployed; see the harness stack outputs.
HARNESS_ARN={c.harness_arn}
HARNESS_ENDPOINT={c.harness_endpoint}
ALLOWED_MODEL_IDS={json.dumps(list(c.model_ids))}
CORS_ORIGINS=http://localhost:5173

# Cognito does not exist until the auth stack is deployed, so local runs skip
# authentication. Ignored when running as a deployed ECS task.
LOCAL_AUTH_BYPASS=true
"""


def frontend_env(c: config.Config) -> str:
    return f"""\
# Generated by scripts/setup.py from project.toml. Local development only.
# Only what the bundle needs to boot; everything else comes from
# GET /api/v1/configuration at runtime.
VITE_COGNITO_REGION={c.aws_region}
# Filled from the auth stack outputs after the first deploy.
VITE_COGNITO_USER_POOL_ID=
VITE_COGNITO_APP_CLIENT_ID=
VITE_COGNITO_DOMAIN=
"""


def main() -> int:
    try:
        c = config.load()
    except (ValueError, KeyError) as e:
        print(f"project.toml is invalid: {e}", file=sys.stderr)
        return 1

    if BACKEND_ENV.exists() and FRONTEND_ENV.exists():
        print(f"Setup is already complete for '{c.name}'. Nothing to do.")
        return 0

    for path, content in ((BACKEND_ENV, backend_env(c)), (FRONTEND_ENV, frontend_env(c))):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"  wrote {path.relative_to(ROOT)}")
    if c.deploys_starter_harness:
        harness_files.write(c, ROOT / "harness")
        print("  wrote harness/ agentcore config")

    print(f"""
Project '{c.name}' configured for {c.aws_account} / {c.aws_region}.
  stacks:  {c.roles_stack}, {c.auth_stack}, {c.data_stack}, {c.app_stack}
  tables:  {c.sessions_table}, {c.items_table}
  harness: {c.harness_stack if c.deploys_starter_harness else c.harness_arn} (endpoint {c.harness_endpoint})

Next: python scripts/bootstrap.py   # once per AWS account
""")

    Path(__file__).unlink()
    print("scripts/setup.py removed itself; commit the result.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
